/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mangroven.hotel.view.jframe;

import com.jidesoft.icons.NetworkIconSet;
import com.mangroven.hotel.controller.ControllerFactory;
import com.mangroven.hotel.controller.custom.ValidationController;
import com.mangroven.hotel.jasper.main.JasperReportView;
import com.mangroven.hotel.view.jpanel.publicPanel;
import com.mangroven.hotel.view.jpanel.reports;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileView;
import javax.swing.plaf.FileChooserUI;
import net.codejava.swing.mail.EmailAttachmentSender;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author Athukorala
 */
public class invoice extends javax.swing.JFrame {
    private ValidationController cntrlValidation;
    int yMouse;
    int xMouse;

    /**
     * Creates new form invoice
     */
    public invoice() {
        initComponents();
        setLocationRelativeTo(null);
        systemDate();
        cntrlValidation = (ValidationController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.VALIDATION);
    }

    private void systemDate() {
        Date d1 = new Date(); //java.util.Date ->get Current date and time
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String formatDate = df.format(d1);
        txtDate.setText(formatDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtLKRSale = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblPrint = new javax.swing.JLabel();
        lblClear = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtComm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDes = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        txtSite = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtUSDSale = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLKR = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(98, 84, 84));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(222, 222, 222));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Room Sale");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 125, 36));

        txtLKRSale.setBackground(new java.awt.Color(45, 147, 229));
        txtLKRSale.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtLKRSale.setForeground(new java.awt.Color(255, 255, 255));
        txtLKRSale.setBorder(null);
        txtLKRSale.setOpaque(false);
        txtLKRSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLKRSaleMouseClicked(evt);
            }
        });
        txtLKRSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLKRSaleActionPerformed(evt);
            }
        });
        txtLKRSale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLKRSaleKeyTyped(evt);
            }
        });
        jPanel8.add(txtLKRSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 80, 30));
        jPanel8.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 80, 10));
        jPanel8.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 290, 10));

        jLabel10.setBackground(new java.awt.Color(204, 255, 204));
        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Attach_30px.png"))); // NOI18N
        jLabel10.setText("  Attachment");
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 120, 30));

        jLabel11.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(252, 254, 152));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Purchase Order_30px.png"))); // NOI18N
        jLabel11.setText("    Invoice");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 31));

        jLabel13.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Description");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 125, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Cancel_30px_1.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 30, 30));

        lblPrint.setBackground(new java.awt.Color(0, 100, 194));
        lblPrint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrint.setForeground(new java.awt.Color(255, 255, 255));
        lblPrint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrint.setText("Print");
        lblPrint.setOpaque(true);
        lblPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPrintMouseExited(evt);
            }
        });
        jPanel8.add(lblPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 90, 30));

        lblClear.setBackground(new java.awt.Color(255, 0, 12));
        lblClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblClear.setForeground(new java.awt.Color(255, 255, 255));
        lblClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClear.setText("Clear");
        lblClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClear.setOpaque(true);
        lblClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClearMouseExited(evt);
            }
        });
        jPanel8.add(lblClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 80, 30));

        txtDate.setBackground(new java.awt.Color(0, 153, 153));
        txtDate.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        txtDate.setForeground(new java.awt.Color(255, 255, 255));
        txtDate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        jPanel8.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 90, 30));

        txtComm.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtComm.setForeground(new java.awt.Color(255, 255, 255));
        txtComm.setBorder(null);
        txtComm.setOpaque(false);
        txtComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommActionPerformed(evt);
            }
        });
        txtComm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCommKeyTyped(evt);
            }
        });
        jPanel8.add(txtComm, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 90, 30));

        txtDes.setColumns(20);
        txtDes.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtDes.setRows(5);
        txtDes.setOpaque(false);
        jScrollPane1.setViewportView(txtDes);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 300, 90));

        jLabel16.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Email");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 56, 125, 20));

        txtSite.setBackground(new java.awt.Color(45, 147, 229));
        txtSite.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtSite.setForeground(new java.awt.Color(255, 255, 255));
        txtSite.setBorder(null);
        txtSite.setOpaque(false);
        txtSite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSiteMouseClicked(evt);
            }
        });
        txtSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSiteActionPerformed(evt);
            }
        });
        jPanel8.add(txtSite, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 290, 30));
        jPanel8.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 90, 10));

        txtUSDSale.setBackground(new java.awt.Color(45, 147, 229));
        txtUSDSale.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtUSDSale.setForeground(new java.awt.Color(255, 255, 255));
        txtUSDSale.setBorder(null);
        txtUSDSale.setOpaque(false);
        txtUSDSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUSDSaleMouseClicked(evt);
            }
        });
        txtUSDSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUSDSaleActionPerformed(evt);
            }
        });
        txtUSDSale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUSDSaleKeyTyped(evt);
            }
        });
        jPanel8.add(txtUSDSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 100, 30));
        jPanel8.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 90, 10));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USD");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 30, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LKR");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("USD");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 30, -1));

        lblEmail.setBackground(new java.awt.Color(0, 153, 0));
        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Send Email");
        lblEmail.setOpaque(true);
        lblEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEmailMouseExited(evt);
            }
        });
        jPanel8.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 90, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("1 USD = LKR");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, 20));

        txtLKR.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtLKR.setForeground(new java.awt.Color(255, 255, 255));
        txtLKR.setText("150");
        txtLKR.setBorder(null);
        txtLKR.setOpaque(false);
        jPanel8.add(txtLKR, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 50, 20));
        jPanel8.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 30, 20));

        jLabel12.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Commission");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 125, 30));

        txtPath.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPath.setForeground(new java.awt.Color(255, 255, 255));
        txtPath.setBorder(null);
        txtPath.setOpaque(false);
        jPanel8.add(txtPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 350, -1));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 390));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/loginPng.png"))); // NOI18N
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLKRSaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLKRSaleMouseClicked

    }//GEN-LAST:event_txtLKRSaleMouseClicked

    private void txtLKRSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLKRSaleActionPerformed

    }//GEN-LAST:event_txtLKRSaleActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        //  format();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void lblPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrintMouseClicked
      print();

    }//GEN-LAST:event_lblPrintMouseClicked

    private void lblPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrintMouseEntered
        lblPrint.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_lblPrintMouseEntered

    private void lblPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrintMouseExited
        lblPrint.setForeground(Color.white);         // TODO add your handling code here:
    }//GEN-LAST:event_lblPrintMouseExited

    private void lblClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearMouseClicked
        clear();
    }//GEN-LAST:event_lblClearMouseClicked

    private void lblClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearMouseEntered
        lblClear.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_lblClearMouseEntered

    private void lblClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearMouseExited
        lblClear.setForeground(Color.white);
    }//GEN-LAST:event_lblClearMouseExited

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel2MouseMoved

    private void txtSiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSiteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSiteMouseClicked

    private void txtSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSiteActionPerformed
 try {
            String email = txtSite.getText();
            boolean result = cntrlValidation.checkEmail(email);
            if (result) {
               txtDes.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Email Number");
                txtSite.requestFocus();

            }
        } catch (Exception ex) {
            Logger.getLogger(publicPanel.class.getName()).log(Level.SEVERE, null, ex);
        }



       
    }//GEN-LAST:event_txtSiteActionPerformed

    private void txtUSDSaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUSDSaleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUSDSaleMouseClicked

    private void txtUSDSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUSDSaleActionPerformed
        if (txtUSDSale.getText().equals("")) {
            txtUSDSale.requestFocus();
        } else {
            txtComm.requestFocus();
            double a = Double.parseDouble(txtLKR.getText());
            double b = Double.parseDouble(txtUSDSale.getText());
            double tot = a * b;
            txtLKRSale.setText(tot + "");
        }
    }//GEN-LAST:event_txtUSDSaleActionPerformed

    private void lblEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmailMouseClicked
        if (txtSite.getText().equals("") || txtPath.getText().equals("")) {
            JOptionPane.showMessageDialog(invoice.this, " Not Complete ", "Error!", JOptionPane.WARNING_MESSAGE);
        } else {
            lblEmail();
            

        }

    }//GEN-LAST:event_lblEmailMouseClicked

    private void lblEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmailMouseEntered
        lblEmail.setForeground(Color.black);
    }//GEN-LAST:event_lblEmailMouseEntered

    private void lblEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmailMouseExited
        lblEmail.setForeground(Color.white);
    }//GEN-LAST:event_lblEmailMouseExited

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtUSDSaleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUSDSaleKeyTyped
        char c = evt.getKeyChar();
        int d = evt.getKeyCode();
        if (Character.isDigit(c) || c == KeyEvent.VK_PERIOD || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_ENTER/*||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)||d==KeyEvent.VK_PERIOD||d==evt.VK_END||d==evt.VK_HOME*/) {

        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtUSDSaleKeyTyped

    private void txtCommKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCommKeyTyped
        char c = evt.getKeyChar();
        int d = evt.getKeyCode();
        if (Character.isDigit(c) || c == KeyEvent.VK_PERIOD || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_ENTER/*||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)||d==KeyEvent.VK_PERIOD||d==evt.VK_END||d==evt.VK_HOME*/) {

        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtCommKeyTyped

    private void txtLKRSaleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLKRSaleKeyTyped
        char c = evt.getKeyChar();
        int d = evt.getKeyCode();
        if (Character.isDigit(c) || c == KeyEvent.VK_PERIOD || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_ENTER/*||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)||d==KeyEvent.VK_PERIOD||d==evt.VK_END||d==evt.VK_HOME*/) {

        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtLKRSaleKeyTyped

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
jLabel10.setForeground(new Color(333333));
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
      jLabel10.setForeground(Color.red);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
JFileChooser ui=new JFileChooser();
ui.setCurrentDirectory(new File(System.getProperty("user.home")));


int result=ui.showOpenDialog(jPanel5);
if(result==JFileChooser.APPROVE_OPTION){
    File select=ui.getSelectedFile();
    txtPath.setText(select+"");
}


    }//GEN-LAST:event_jLabel10MouseClicked

    private void txtCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommActionPerformed
print();        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblClear;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPrint;
    private javax.swing.JTextField txtComm;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextArea txtDes;
    private javax.swing.JTextField txtLKR;
    private javax.swing.JTextField txtLKRSale;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtSite;
    private javax.swing.JTextField txtUSDSale;
    // End of variables declaration//GEN-END:variables

    private void clear() {

        txtComm.setText("");
        txtDes.setText("");
        txtLKRSale.setText("");
        txtSite.setText("");
        txtUSDSale.setText("");
    }

    private void lblPrint() {

        try {
            JasperReport main = (JasperReport) JRLoader.loadObject(reports.class.getResourceAsStream("/com/mangroven/hotel/jasper/reports/invoice.jasper"));
            Connection conn;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/MangrovenNew", "root", "4241");

            HashMap<String, Object> parameters = new HashMap<>();
            parameters.put("txtDate", txtDate.getText());
            parameters.put("txtRoom", txtUSDSale.getText());
            parameters.put("txtComm", txtComm.getText());
            parameters.put("txtLKR", txtLKRSale.getText());
            parameters.put("txtDes", txtDes.getText());

            JasperPrint fill = JasperFillManager.fillReport(main, parameters, new JREmptyDataSource());
            //JasperPrint filledReport = JasperFillManager.fillReport(mainReport, parameters, new JREmptyDataSource());
            JasperReportView view = new JasperReportView(fill);
                  
            view.setVisible(true);
            
            
            
        } catch (JRException ex) {
            Logger.getLogger(invoice.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(invoice.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(invoice.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void lblEmail() {
    
        String email=txtSite.getText();
        String path=txtPath.getText();
        EmailAttachmentSender send=new EmailAttachmentSender();
        send.attachment(email,path);
    }

    private void print() {
          if (txtDes.getText().equals("") || txtComm.getText().equals("") || txtLKRSale.getText().equals("") || txtSite.getText().equals("") || txtUSDSale.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " Not Complete ", "Error!", JOptionPane.WARNING_MESSAGE);
        } else {
            lblPrint();

        }
    }
}
