/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mangroven.hotel.view.jframe;

import com.mangroven.hotel.controller.ControllerFactory;
import com.mangroven.hotel.controller.custom.PasswordController;
import com.mangroven.hotel.dto.PasswordDTO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Athukorala
 */
public class loginNew extends javax.swing.JFrame {

    private Timer tmr;

    int xMouse;
    int yMouse;
    private PasswordController psw;

    /**
     * Creates new form loginNew
     */
    public loginNew() {
        initComponents();
        psw = (PasswordController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.PASSWORD);
        setLocationRelativeTo(null);
        txtPassword.setEnabled(false);
        jPanel5.setVisible(false);
        jProgressBar1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnGo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        newPassword = new javax.swing.JPasswordField();
        verify = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        password = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        lblName = new javax.swing.JLabel();
        lblOld = new javax.swing.JLabel();
        lblNew = new javax.swing.JLabel();
        lblVeri = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblFormat = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUser1 = new javax.swing.JLabel();
        lblPass1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblB1 = new javax.swing.JLabel();
        lblA1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Minus_30px.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, 30));

        jProgressBar1.setForeground(new java.awt.Color(255, 255, 0));
        jProgressBar1.setBorder(null);
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 160, 20));

        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Help_48px.png"))); // NOI18N
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 60, 40));

        lblPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Help_48px.png"))); // NOI18N
        jPanel1.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 70, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Cancel_30px_1.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 30, 30));

        txtUser.setBackground(new java.awt.Color(109, 175, 240));
        txtUser.setFont(new java.awt.Font("Adobe Hebrew", 1, 18)); // NOI18N
        txtUser.setBorder(null);
        txtUser.setOpaque(false);
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 140, 20));

        txtPassword.setBackground(new java.awt.Color(206, 230, 239));
        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPassword.setBorder(null);
        txtPassword.setOpaque(false);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 140, 20));

        btnGo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGoMouseClicked(evt);
            }
        });
        jPanel1.add(btnGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 40, 40));

        jLabel8.setToolTipText("Change The Password");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 40, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 160, -1));

        jLabel9.setToolTipText("Change The Password");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 50, 50));

        jLabel5.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(14, 7, 82));
        jLabel5.setText("Mangroven Login");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 3, 180, 30));

        lblB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblBMouseMoved(evt);
            }
        });
        jPanel1.add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 400));
        jPanel1.add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 4, 560, 30));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setOpaque(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/lock.png"))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 160, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/login.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 791, -1));

        jPanel3.add(jPanel1, "card2");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(98, 84, 84));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(222, 222, 222));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("User Name");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 83, 125, 36));

        name.setBackground(new java.awt.Color(45, 147, 229));
        name.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setBorder(null);
        name.setOpaque(false);
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel8.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 83, 174, 36));
        jPanel8.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 267, 174, 8));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Verify Password");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 281, 125, 36));
        jPanel8.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 125, 174, 10));

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("New Password");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 210, 125, 36));

        newPassword.setBackground(new java.awt.Color(45, 147, 229));
        newPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newPassword.setForeground(new java.awt.Color(255, 255, 255));
        newPassword.setBorder(null);
        newPassword.setEnabled(false);
        newPassword.setOpaque(false);
        newPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newPasswordMouseClicked(evt);
            }
        });
        newPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordActionPerformed(evt);
            }
        });
        jPanel8.add(newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 210, 174, 36));

        verify.setBackground(new java.awt.Color(45, 147, 229));
        verify.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        verify.setForeground(new java.awt.Color(255, 255, 255));
        verify.setBorder(null);
        verify.setEnabled(false);
        verify.setOpaque(false);
        verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyActionPerformed(evt);
            }
        });
        jPanel8.add(verify, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 294, 174, 23));
        jPanel8.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 323, 172, -1));

        jLabel11.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(252, 254, 152));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/lock.png"))); // NOI18N
        jLabel11.setText("    Change Password");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 200, 31));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 399));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 0, -1, 399));

        password.setBackground(new java.awt.Color(45, 147, 229));
        password.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(null);
        password.setOpaque(false);
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel8.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 153, 174, 31));

        jLabel13.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Old Password");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 153, 125, -1));
        jPanel8.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 189, 174, 10));
        jPanel8.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 83, -1, 33));
        jPanel8.add(lblOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 153, -1, 33));
        jPanel8.add(lblNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 223, -1, 33));
        jPanel8.add(lblVeri, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 281, -1, 36));

        lblId.setText("Pw01");
        jPanel8.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 56, 1, -1));

        lblFormat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFormatMouseClicked(evt);
            }
        });
        jPanel8.add(lblFormat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 20));

        jLabel15.setBackground(new java.awt.Color(255, 0, 12));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Back");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.setOpaque(true);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 80, 30));

        jLabel22.setBackground(new java.awt.Color(0, 153, 0));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("OK");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.setOpaque(true);
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22MouseExited(evt);
            }
        });
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 90, 30));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Cancel_30px.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 50, 40));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/loginPng.png"))); // NOI18N
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 400));

        lblUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Help_48px.png"))); // NOI18N
        jPanel5.add(lblUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 60, 40));

        lblPass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Help_48px.png"))); // NOI18N
        jPanel5.add(lblPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 70, 40));

        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 30, 30));

        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 40, 40));

        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 40, 50));

        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 50, 50));

        jLabel19.setText("Mangroven Login");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 140, -1));

        lblB1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblB1MouseMoved(evt);
            }
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblB1MouseDragged(evt);
            }
        });
        jPanel5.add(lblB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 400));
        jPanel5.add(lblA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 4, 560, 30));

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel9.setOpaque(false);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/lock.png"))); // NOI18N

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/login.png"))); // NOI18N
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 791, -1));

        jPanel3.add(jPanel5, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed

        try {
            PasswordDTO dto = psw.getAllDetail();

            if (txtUser.getText().equals(dto.getUserName())) {
                txtPassword.setEnabled(true);
                txtPassword.requestFocus();

            } else {
                JOptionPane.showMessageDialog(loginNew.this, " Sorry Try Again..");
                txtUser.setText("");

            }// TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(loginNew.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        try {

            PasswordDTO p1 = psw.getAllDetail();

            if (txtPassword.getText().equals(p1.getPassword())) {

                jProgressBar1.setVisible(true);

                tmr = new Timer(150, new ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        jProgressBar1.setValue(jProgressBar1.getValue() + 5);
                        if (jProgressBar1.getValue() >= jProgressBar1.getMaximum()) {
                            try {
                                //this.dispose();
                                tmr.stop();
                                loginNew.this.dispose();
                                mainFrame mq = new mainFrame();
                                mq.setVisible(true);

                                //this.dispose();
                            } catch (SQLException ex) {
                                Logger.getLogger(loginNew.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        }
                    }

                });

                tmr.start();
        // this.dispose();
         /*  mainFrame mq = new mainFrame();
                 mq.setVisible(true);
                 this.dispose();*/
            } else {
                JOptionPane.showMessageDialog(loginNew.this, " Sorry Inncorrect Your Password!");
                txtPassword.setText(null);
            }

            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(loginNew.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnGoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoMouseClicked
        try {
            PasswordDTO c1 = psw.getAllDetail();
            if (txtUser.getText().equals(c1.getUserName()) && txtPassword.getText().equals(c1.getPassword())) {

                jProgressBar1.setVisible(true);

                tmr = new Timer(150, new ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        jProgressBar1.setValue(jProgressBar1.getValue() + 5);
                        if (jProgressBar1.getValue() >= jProgressBar1.getMaximum()) {
                            try {
                                //this.dispose();
                                tmr.stop();
                                loginNew.this.dispose();
                                mainFrame mq = new mainFrame();
                                mq.setVisible(true);

                                //this.dispose();
                            } catch (SQLException ex) {
                                Logger.getLogger(loginNew.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        }
                    }

                });

                tmr.start();
            } else {
                JOptionPane.showMessageDialog(loginNew.this, " Sorry Inncorrect Your Password!");
                txtPassword.setText(null);
            }
        } catch (Exception ex) {
            Logger.getLogger(loginNew.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnGoMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        jPanel5.setVisible(true);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        jPanel5.setVisible(true);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void lblBMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);        // TODO add your handling code here:
    }//GEN-LAST:event_lblBMouseDragged

    private void lblBMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBMouseMoved
        xMouse = evt.getX();
        yMouse = evt.getY();          // TODO add your handling code here:
    }//GEN-LAST:event_lblBMouseMoved

    private void lblB1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblB1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);        // TODO add your handling code here:
    }//GEN-LAST:event_lblB1MouseDragged

    private void lblB1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblB1MouseMoved
        xMouse = evt.getX();
        yMouse = evt.getY();          // TODO add your handling code here:
    }//GEN-LAST:event_lblB1MouseMoved

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        jPanel3.setVisible(true);  //JOptionPane.showMessageDialog(null," Not complete","Error!",JOptionPane.WARNING_MESSAGE);      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        jPanel3.setVisible(true);
        //        JOptionPane.showMessageDialog(null," Not complete","Error!",JOptionPane.WARNING_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked

    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        try {

            PasswordDTO p1 = psw.getAllDetail();

            if (password.getText().equals(p1.getPassword())) {
                lblOld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/AA.png")));
                newPassword.setEnabled(true);
                newPassword.requestFocus();

            } else {
                lblOld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/BB.png")));
                password.requestFocus();
                password.setText("");
            }
        } catch (Exception ex) {
            Logger.getLogger(loginNew.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void verifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyActionPerformed
        try {
            PasswordDTO p1 = psw.getAllDetail();

            if (newPassword.getText().equals(verify.getText()) && password.getText().equals(p1.getPassword())) {
                lblVeri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/AA.png")));
                lblNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/AA.png")));
                add();

            } else {

                lblVeri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/BB.png")));
                JOptionPane.showMessageDialog(loginNew.this, "Incomplete");
                verify.requestFocus();
            }
        } catch (Exception ex) {
            Logger.getLogger(LoginEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_verifyActionPerformed

    private void newPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordActionPerformed
        // if(newPassword.getPassword())
        verify.setEnabled(true);
        verify.requestFocus();
        lblNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Q.png")));
    }//GEN-LAST:event_newPasswordActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        lblName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/AA.png")));
        password.requestFocus();

        /*
         if (name.getText().equals("admin")) {
         String name = txtUser.getText();
         lblName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/AA.png")));
         password.requestFocus();
    
         } else {
         name.setText("");
         lblName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/BB.png")));
         name.requestFocus();
         }*/
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        newPassword.setEnabled(false);
        verify.setEnabled(false);
    }//GEN-LAST:event_passwordMouseClicked

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        newPassword.setEnabled(false);
        verify.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_nameMouseClicked

    private void newPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newPasswordMouseClicked

        verify.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordMouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        try {
            PasswordDTO p1 = psw.getAllDetail();

            if (newPassword.getText().equals(verify.getText()) && password.getText().equals(p1.getPassword())) {
                lblVeri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/AA.png")));
                lblNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/AA.png")));
                add();

            } else {

                lblVeri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/BB.png")));
                JOptionPane.showMessageDialog(loginNew.this, "Incomplete");
                //verify.requestFocus();
            }
        } catch (Exception ex) {
            Logger.getLogger(LoginEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseEntered
        jLabel22.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseEntered

    private void jLabel22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseExited
        jLabel22.setForeground(Color.white);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseExited

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        jPanel5.setVisible(false);
        icon();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void lblFormatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFormatMouseClicked
        format();         // TODO add your handling code here:
    }//GEN-LAST:event_lblFormatMouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        jLabel15.setForeground(Color.black);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        jLabel15.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        this.setState(loginNew.ICONIFIED);
    }//GEN-LAST:event_jLabel23MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    Thread.sleep(500);
                } catch (Exception e) {
                }
                new loginNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnGo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblA1;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblB1;
    private javax.swing.JLabel lblFormat;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNew;
    private javax.swing.JLabel lblOld;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPass1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUser1;
    private javax.swing.JLabel lblVeri;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    private javax.swing.JPasswordField verify;
    // End of variables declaration//GEN-END:variables

    private void add() {
        try {
            String id = lblId.getText();
            String user = name.getText();
            String Verify = verify.getText();

            PasswordDTO p1 = new PasswordDTO(id, user, Verify);
            boolean update = psw.update(p1);
            if (update) {
                JOptionPane.showMessageDialog(loginNew.this, "Ok! Password Changed");
                name.setText("");
                password.setText("");
                newPassword.setText("");
                verify.setText("");
                jPanel5.setVisible(false);
                icon();
            } else {
                JOptionPane.showMessageDialog(loginNew.this, "Sorry TryAgain");
                name.setText("");
                password.setText("");
                newPassword.setText("");
                verify.setText("");
                icon();
            }
        } catch (Exception ex) {
            Logger.getLogger(loginNew.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void format() {
        try {
            String id = "Pw01";
            String user = "";
            String Verify = "";

            PasswordDTO p1 = new PasswordDTO(id, user, Verify);
            boolean update = psw.update(p1);
            if (update) {
                // JOptionPane.showMessageDialog(loginNew.this, "Ok! Password Changed");
                name.setText("");
                password.setText("");
                newPassword.setText("");
                verify.setText("");
                jPanel5.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(loginNew.this, "Sorry TryAgain");

            }
        } catch (Exception ex) {
            Logger.getLogger(loginNew.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void icon() {
        name.setText("");
        password.setText("");
        newPassword.setText("");
        verify.setText("");

        lblVeri.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        lblName.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        lblOld.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        lblNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
    }
}
