/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mangroven.hotel.view.jpanel;

import com.jidesoft.swing.AutoCompletion;
import com.mangroven.hotel.controller.ControllerFactory;
import com.mangroven.hotel.controller.custom.FoodController;
import com.mangroven.hotel.controller.custom.Food_PackageController;
import com.mangroven.hotel.controller.custom.impl.FoodControllerImpl;
import com.mangroven.hotel.controller.custom.impl.Food_PackageControllerImpl;

import com.mangroven.hotel.dao.db.ConnectionFactory;
import com.mangroven.hotel.idGenerator.IDGenerator;
import com.mangroven.hotel.dto.FoodDTO;
import com.mangroven.hotel.dto.Food_PackageDTO;
import com.mangroven.hotel.dto.Food_Package_DetailDTO;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tharindu
 */
public class addNewPackage extends javax.swing.JPanel {

    private Food_PackageController packCntrl;
    private FoodController foodCntrl;

    /**
     * Creates new form addNewPackage
     */
    public addNewPackage() throws IOException, Exception {
        initComponents();
        txtName.requestFocus();
        AutoCompletion ac = new AutoCompletion(comboFID);
        packCntrl = (Food_PackageController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.FOOD_PACKAGE);
        foodCntrl = (FoodController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.FOOD);
        fid();
        edit();
        clear();
        PackageIDGenerator();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        txtPrice = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jPanel16 = new javax.swing.JPanel();
        txtPID = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboFID = new javax.swing.JComboBox<String>();
        jPanel17 = new javax.swing.JPanel();
        txtFName = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jPanel18 = new javax.swing.JPanel();
        txtFPrice = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        btnAdd6 = new javax.swing.JLabel();
        btnAdd5 = new javax.swing.JLabel();
        btnRemove1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(243, 243, 243));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(93, 16, 144));
        jLabel3.setText("Package Name    ");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(93, 16, 144));
        jLabel4.setText("Package Price");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setOpaque(false);

        txtPrice.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        txtPrice.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPrice.setOpaque(false);
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(93, 16, 144));
        jLabel2.setText("Package ID        ");

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setOpaque(false);

        txtName.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtName.setOpaque(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator14)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setOpaque(false);

        txtPID.setEditable(false);
        txtPID.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        txtPID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPID.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtPID.setEnabled(false);
        txtPID.setOpaque(false);
        txtPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator15)
                    .addComponent(txtPID, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(jLabel1))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(txtPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/down.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Noto Sans", 0, 10)); // NOI18N
        jLabel6.setText("LKR");

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(192, 1, 10));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/image1.gif"))); // NOI18N
        jLabel5.setText("   Build Food Package ");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food ID", "Food Name"
            }
        ));
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);

        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(93, 16, 144));
        jLabel9.setText("Food Name    ");

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(93, 16, 144));
        jLabel10.setText("Unit Price");

        jLabel11.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(93, 16, 144));
        jLabel11.setText("Food ID        ");

        comboFID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboFID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFIDItemStateChanged(evt);
            }
        });
        comboFID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFIDActionPerformed(evt);
            }
        });

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setOpaque(false);

        txtFName.setEditable(false);
        txtFName.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        txtFName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtFName.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtFName.setOpaque(false);
        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator16)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setOpaque(false);

        txtFPrice.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        txtFPrice.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtFPrice.setOpaque(false);
        txtFPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator17)
                    .addComponent(txtFPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addGap(98, 98, 98))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(txtFPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        btnAdd6.setBackground(new java.awt.Color(18, 151, 16));
        btnAdd6.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        btnAdd6.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdd6.setText("Add");
        btnAdd6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAdd6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd6.setOpaque(true);
        btnAdd6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdd6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdd6MouseExited(evt);
            }
        });

        btnAdd5.setBackground(new java.awt.Color(250, 1, 15));
        btnAdd5.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        btnAdd5.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdd5.setText("Remove");
        btnAdd5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAdd5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd5.setOpaque(true);
        btnAdd5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdd5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdd5MouseExited(evt);
            }
        });

        btnRemove1.setBackground(new java.awt.Color(212, 191, 29));
        btnRemove1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        btnRemove1.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRemove1.setText("Clear");
        btnRemove1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRemove1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemove1.setOpaque(true);
        btnRemove1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemove1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRemove1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRemove1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboFID, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(jLabel9)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1039, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(434, 434, 434))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnAdd6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemove1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboFID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, -1, 560));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1108, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        if (txtName.getText().equals("")) {
            txtName.requestFocus();
        } else {
            txtPrice.requestFocus();
        }
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPIDActionPerformed

    }//GEN-LAST:event_txtPIDActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked

    }//GEN-LAST:event_jLabel16MouseClicked

    private void btnAdd5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd5MouseClicked
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        if (table.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Please Select an item to remove", "Remove an item?", JOptionPane.WARNING_MESSAGE);
        } else {

            dtm.removeRow(table.getSelectedRow());

        }
    }//GEN-LAST:event_btnAdd5MouseClicked

    private void btnAdd5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd5MouseExited
     btnAdd5.setForeground(Color.white);   // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd5MouseExited

    private void btnAdd5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd5MouseEntered
    btnAdd5.setForeground(Color.black);    // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd5MouseEntered

    private void comboFIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFIDItemStateChanged
        String food = (String) comboFID.getSelectedItem();

        try {

            FoodDTO cust = foodCntrl.search(food);
            txtFName.setText(cust.getFood_Name());
            txtFPrice.setText(cust.getUnit_Price() + "");
            txtFName.requestFocus();
        } catch (SQLException e) {
            // System.out.println(e);
        } catch (ClassNotFoundException e) {
            // System.out.println(e);
        } catch (IOException ex) {
            Logger.getLogger(setNewPackage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(setNewPackage.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtFPrice.requestFocus();

    }//GEN-LAST:event_comboFIDItemStateChanged

    private void btnAdd6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd6MouseClicked
        if (txtName.getText().equals("") | txtPrice.getText().equals("") | table.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Sorry! Incomplete...", "Build Package", JOptionPane.WARNING_MESSAGE);

        } else {

            try {
                String pid = txtPID.getText();
                String name = txtName.getText();
                double price = Double.parseDouble(txtPrice.getText());

                DefaultTableModel dtm = (DefaultTableModel) table.getModel();
                ArrayList<Food_Package_DetailDTO> detail = new ArrayList<>();
                for (int i = 0; i < dtm.getRowCount(); i++) {
                    String fid = (String) dtm.getValueAt(i, 0);
                    Food_Package_DetailDTO fdDto = new Food_Package_DetailDTO(pid, fid);
                    detail.add(fdDto);
                }
                Food_PackageDTO foodPackge = new Food_PackageDTO(pid, name, price, detail);
                System.out.println(pid + " " + name + " " + price + " " + detail);

                boolean isAdd = packCntrl.transaction(foodPackge);

                if (isAdd) {
                    JOptionPane.showMessageDialog(null, "Added Success");
                    clear();

                } else {
                    JOptionPane.showMessageDialog(null, "Added Failes");
                }
            } catch (Exception ex) {
                Logger.getLogger(skipPanelAssemble.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btnAdd6MouseClicked

    private void btnAdd6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd6MouseExited
  btnAdd6.setForeground(Color.white);      // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd6MouseExited

    private void btnAdd6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd6MouseEntered
btnAdd6.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd6MouseEntered

    private void btnRemove1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemove1MouseClicked
        clear();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemove1MouseClicked

    private void btnRemove1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemove1MouseExited
     btnRemove1.setForeground(Color.white);   // TODO add your handling code here:
    }//GEN-LAST:event_btnRemove1MouseExited

    private void btnRemove1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemove1MouseEntered
      btnRemove1.setForeground(Color.black);  // TODO add your handling code here:
    }//GEN-LAST:event_btnRemove1MouseEntered

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        String code = (String) comboFID.getSelectedItem();
        String name = txtFName.getText();

        for (int i = 0; i < dtm.getRowCount(); i++) {
            String Code = (String) dtm.getValueAt(i, 0);
            if (Code.equals(code)) {
                dtm.removeRow(i);
                //JOptionPane.showMessageDialog(null,"Already has been Success");
            }
        }
        Object[] rowData = {code, name};
        dtm.addRow(rowData);        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
if(txtPrice.getText().equals("")){
    txtPrice.requestFocus();
}else{
        comboFID.requestFocus();   
}
    }//GEN-LAST:event_txtPriceActionPerformed

    private void comboFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFIDActionPerformed
        txtFPrice.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_comboFIDActionPerformed

    private void txtFPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFPriceActionPerformed

        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        String code = (String) comboFID.getSelectedItem();
        String name = txtFName.getText();

        for (int i = 0; i < dtm.getRowCount(); i++) {
            String Code = (String) dtm.getValueAt(i, 0);
            if (Code.equals(code)) {
                dtm.removeRow(i);
                //JOptionPane.showMessageDialog(null,"Already has been Success");
            }
        }
        Object[] rowData = {code, name};
        dtm.addRow(rowData);
        comboFID.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtFPriceActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        /*   int key = evt.getKeyCode();
        if(Character.isLetter(key)||(key >= evt.VK_A && key <= evt.VK_Z)||key==evt.VK_SHIFT||key==evt.VK_SPACE||key==evt.VK_BACK_SPACE||key==evt.VK_END||key==evt.VK_DELETE||key==evt.VK_HOME||key==evt.VK_LEFT||key==evt.VK_CAPS_LOCK){
        
        }else{
        txtName.setText("");
        }*/
              // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        /*   int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9)||key==evt.VK_BACK_SPACE||key==evt.VK_PERIOD||key==evt.VK_DELETE||key==evt.VK_HOME||key==evt.VK_END||key==evt.VK_LEFT||key==evt.VK_CAPS_LOCK) {
        
        
        } else {
        txtPrice.setText("");
        
        
        
        } */      // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceKeyReleased

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
    char c = evt.getKeyChar();
        int d = evt.getKeyCode();
        if (Character.isDigit(c) || c == KeyEvent.VK_PERIOD || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_ENTER/*||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)||d==KeyEvent.VK_PERIOD||d==evt.VK_END||d==evt.VK_HOME*/) {

        } else {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceKeyTyped

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
 char key = evt.getKeyChar();
          if(Character.isLetter(key)||(key >= KeyEvent.VK_A && key <= KeyEvent.VK_Z)||key==KeyEvent.VK_SHIFT||key==KeyEvent.VK_SPACE||key==evt.VK_BACK_SPACE||key==evt.VK_END||key==evt.VK_DELETE||key==evt.VK_HOME||key==evt.VK_LEFT||key==KeyEvent.VK_CAPS_LOCK||key==evt.VK_RIGHT||key==evt.VK_DOWN||key==evt.VK_UP){
            
        }else{
           getToolkit().beep();
           evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdd5;
    private javax.swing.JLabel btnAdd6;
    private javax.swing.JLabel btnRemove1;
    private javax.swing.JComboBox<String> comboFID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtFPrice;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPID;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables

    public void PackageIDGenerator() throws IOException {
        try {
            String pid;
            pid = IDGenerator.getNewID("Food_Package", "PID", "P");
            txtPID.setText(pid);
        } catch (SQLException ex) {
            Logger.getLogger(addGuestPanel1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(addGuestPanel1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void fid() throws IOException, Exception {
        try {
            ArrayList<FoodDTO> foodList = foodCntrl.getAllID();
            for (int i = 0; i < foodList.size(); i++) {
                FoodDTO reserve = (FoodDTO) foodList.get(i);
                comboFID.addItem(reserve.getFID());

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(setNewPackage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(setNewPackage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void clear() {
        try {
            txtPrice.setText("");
            txtName.setText("");
            PackageIDGenerator();
            DefaultTableModel dtm = (DefaultTableModel) table.getModel();
            dtm.setRowCount(0);
            table.removeAll();
        } catch (IOException ex) {
            Logger.getLogger(skipPanelAssemble.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void edit() {
        txtPID.setEnabled(false);
        txtPID.setDisabledTextColor(new Color(128, 128, 128));
        txtFName.setEnabled(false);
        txtFName.setDisabledTextColor(new Color(128, 128, 128));
        // txtFPrice.setEnabled(false);
        txtFPrice.setDisabledTextColor(new Color(128, 128, 128));
    }
}
