/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mangroven.hotel.view.jpanel;

import com.mangroven.hotel.view.jpanel.ModifyPayment;
import com.jidesoft.swing.AutoCompletion;
import com.mangroven.hotel.controller.ControllerFactory;
import com.mangroven.hotel.controller.custom.GuestController;
import com.mangroven.hotel.controller.custom.PaymentController;
import com.mangroven.hotel.controller.custom.QueryController;
import com.mangroven.hotel.controller.custom.ReservationController;
import com.mangroven.hotel.controller.custom.RoomController;
import com.mangroven.hotel.dao.DAOFactory;
import com.mangroven.hotel.dao.db.ConnectionFactory;
import com.mangroven.hotel.dto.FoodDTO;
import com.mangroven.hotel.dto.GuestDTO;
import com.mangroven.hotel.dto.PaymentDTO;
import com.mangroven.hotel.dto.ReservationDTO;
import com.mangroven.hotel.dto.RoomDTO;
import com.mangroven.hotel.jasper.main.JasperReportView;
import java.awt.Color;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author tharindu
 */
public class modReservePanel extends javax.swing.JPanel {

    private Connection conn;

    private static String rsid;
    private static String oldPrice;
    private static String roomid;
    private static String payid;

    private String oldRid;

    private PaymentController payCntrl;
    private ReservationController resvCntrl;
    private RoomController roomCntrl;
    private QueryController queryCntrl;
    private GuestController guestCntrl;

    private long x;

    /**
     * Creates new form modReservePanel
     */
    public modReservePanel() throws Exception {

        initComponents();
        conn = ConnectionFactory.getInstance().getConnection();
        guestCntrl = (GuestController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.GUEST);
        payCntrl = (PaymentController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.PAYMENT);
        queryCntrl = (QueryController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.QUERY);
        resvCntrl = (ReservationController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.RESERVATION);
        roomCntrl = (RoomController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.ROOM);
        AutoCompletion ac1 = new AutoCompletion(comboRsid);
        AutoCompletion ac2 = new AutoCompletion(comboGuest);
        AutoCompletion ac3 = new AutoCompletion(comboPerson);
        rsidLoard();
        gidLoard();
        edit();
        //
        searchPrice();
        icon();
        lblRoom2.setForeground(Color.red);
        
         Calendar cal=Calendar.getInstance();
        cal.add(Calendar.DATE,0);
        datePickerIn.getMonthView().setLowerBound(cal.getTime());
        
         Calendar cal2=Calendar.getInstance();
        cal2.add(Calendar.DATE,0);
        datePickerIn1.getMonthView().setLowerBound(cal2.getTime());

        // view();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        txtIN = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        datePickerIn = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        comboGuest = new javax.swing.JComboBox();
        jPanel11 = new javax.swing.JPanel();
        txtRoom = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        comboPerson = new javax.swing.JComboBox();
        comboRsid = new javax.swing.JComboBox<String>();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        txtOUT = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        datePickerIn1 = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lblDelete = new javax.swing.JLabel();
        btnEdit1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        txtOldPrice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        txtNewPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDay = new javax.swing.JTextField();
        txtRoomPrice = new javax.swing.JTextField();
        lblRoomIcon = new javax.swing.JLabel();
        lblGuestName = new javax.swing.JLabel();
        lblDelete1 = new javax.swing.JLabel();
        txtDesription = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblRoom2 = new javax.swing.JLabel();
        lblRoom = new javax.swing.JLabel();
        lblRoom3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));

        mainPanel.setBackground(new java.awt.Color(254, 254, 254));

        mainPanel1.setBackground(new java.awt.Color(254, 254, 254));

        jPanel6.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(243, 243, 243));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(55, 14, 169));
        jLabel3.setText("Guest ID   ");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(55, 14, 169));
        jLabel4.setText("Check In Date   ");

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(55, 14, 169));
        jLabel6.setText("Check Out Date   ");

        jPanel9.setBackground(new java.awt.Color(236, 236, 236));
        jPanel9.setOpaque(false);

        txtIN.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        txtIN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtIN.setEnabled(false);
        txtIN.setOpaque(false);
        txtIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtINMouseClicked(evt);
            }
        });
        txtIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtINActionPerformed(evt);
            }
        });

        datePickerIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datePickerInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator6)
                    .addComponent(txtIN, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(datePickerIn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(datePickerIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(txtIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(55, 14, 169));
        jLabel7.setText("Room ID   ");

        jLabel2.setBackground(new java.awt.Color(55, 14, 169));
        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(55, 14, 169));
        jLabel2.setText("Reservation ID   ");

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(152, 5, 5));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/image1.gif"))); // NOI18N
        jLabel1.setText("    Modify Room Reservation");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel10.setBackground(new java.awt.Color(236, 236, 236));
        jPanel10.setOpaque(false);

        comboGuest.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        comboGuest.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboGuestItemStateChanged(evt);
            }
        });
        comboGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboGuestMouseClicked(evt);
            }
        });
        comboGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGuestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboGuest, 0, 124, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(comboGuest, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(236, 236, 236));
        jPanel11.setOpaque(false);

        txtRoom.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        txtRoom.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtRoom.setDisabledTextColor(new java.awt.Color(128, 128, 128));
        txtRoom.setOpaque(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator8)
                    .addComponent(txtRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(55, 14, 169));
        jLabel8.setText("Persons");

        jPanel12.setBackground(new java.awt.Color(236, 236, 236));
        jPanel12.setOpaque(false);

        comboPerson.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        comboPerson.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        comboPerson.setOpaque(false);
        comboPerson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboPersonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(comboPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(comboPerson, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        comboRsid.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        comboRsid.setBorder(null);
        comboRsid.setOpaque(false);
        comboRsid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboRsidItemStateChanged(evt);
            }
        });
        comboRsid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboRsidMouseClicked(evt);
            }
        });
        comboRsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRsidActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setOpaque(false);

        txtOUT.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        txtOUT.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtOUT.setEnabled(false);
        txtOUT.setOpaque(false);
        txtOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOUTMouseClicked(evt);
            }
        });
        txtOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOUTActionPerformed(evt);
            }
        });

        datePickerIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datePickerIn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator5)
                    .addComponent(txtOUT, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(datePickerIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePickerIn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " Room ID", " Room_Name", " Room_Description", " Room_Price"
            }
        ));
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel5.setBackground(new java.awt.Color(0, 197, 255));
        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Search");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });

        lblDelete.setBackground(new java.awt.Color(255, 0, 12));
        lblDelete.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblDelete.setForeground(new java.awt.Color(255, 255, 255));
        lblDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDelete.setText("Delete");
        lblDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDelete.setOpaque(true);
        lblDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDeleteMouseExited(evt);
            }
        });

        btnEdit1.setBackground(new java.awt.Color(205, 149, 1));
        btnEdit1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        btnEdit1.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEdit1.setText("Edit");
        btnEdit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit1.setOpaque(true);
        btnEdit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEdit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEdit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEdit1MouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(55, 14, 169));
        jLabel10.setText("New Price");

        jPanel13.setBackground(new java.awt.Color(236, 236, 236));
        jPanel13.setOpaque(false);

        txtOldPrice.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        txtOldPrice.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtOldPrice.setDisabledTextColor(new java.awt.Color(128, 128, 128));
        txtOldPrice.setOpaque(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtOldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(txtOldPrice)
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(55, 14, 169));
        jLabel11.setText("Old Price");

        jPanel14.setBackground(new java.awt.Color(236, 236, 236));
        jPanel14.setOpaque(false);

        txtNewPrice.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        txtNewPrice.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNewPrice.setDisabledTextColor(new java.awt.Color(128, 128, 128));
        txtNewPrice.setOpaque(false);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(txtNewPrice)
                .addContainerGap())
        );

        jLabel9.setForeground(new java.awt.Color(140, 140, 140));
        jLabel9.setText("Room Price");

        jLabel12.setForeground(new java.awt.Color(140, 140, 140));
        jLabel12.setText("Selected Days");

        txtDay.setBorder(null);
        txtDay.setDisabledTextColor(new java.awt.Color(103, 103, 103));
        txtDay.setEnabled(false);
        txtDay.setOpaque(false);
        txtDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDayActionPerformed(evt);
            }
        });

        txtRoomPrice.setBorder(null);
        txtRoomPrice.setDisabledTextColor(new java.awt.Color(103, 103, 103));
        txtRoomPrice.setEnabled(false);
        txtRoomPrice.setOpaque(false);
        txtRoomPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomPriceActionPerformed(evt);
            }
        });

        lblRoomIcon.setBackground(new java.awt.Color(236, 236, 236));
        lblRoomIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRoomIcon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblRoomIcon.setOpaque(true);

        lblGuestName.setForeground(new java.awt.Color(140, 140, 140));
        lblGuestName.setText("Room Price");

        lblDelete1.setBackground(new java.awt.Color(212, 191, 29));
        lblDelete1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblDelete1.setForeground(new java.awt.Color(255, 255, 255));
        lblDelete1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDelete1.setText("Clear");
        lblDelete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDelete1.setOpaque(true);
        lblDelete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDelete1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDelete1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDelete1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(comboRsid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblRoomIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(79, 79, 79)
                                        .addComponent(txtDesription, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(172, 172, 172))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGap(88, 88, 88)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(95, 95, 95)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(62, 62, 62)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1044, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblGuestName, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(593, 593, 593)
                                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(241, 241, 241)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtRoomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150)
                                .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(44, 44, 44))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboRsid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblGuestName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRoomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDesription))
                                        .addGap(10, 10, 10))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPrice))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblRoomIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(41, 41, 41)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))))
        );

        javax.swing.GroupLayout mainPanel1Layout = new javax.swing.GroupLayout(mainPanel1);
        mainPanel1.setLayout(mainPanel1Layout);
        mainPanel1Layout.setHorizontalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1096, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 233, Short.MAX_VALUE))
            .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanel1Layout.createSequentialGroup()
                    .addGap(1101, 1101, 1101)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(43, Short.MAX_VALUE)))
        );
        mainPanel1Layout.setVerticalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        lblRoom2.setBackground(new java.awt.Color(254, 254, 254));
        lblRoom2.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lblRoom2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRoom2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/down.png"))); // NOI18N
        lblRoom2.setText("                        Modify Room Reservation");
        lblRoom2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblRoom2.setOpaque(true);
        lblRoom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRoom2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRoom2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRoom2MouseExited(evt);
            }
        });
        jPanel1.add(lblRoom2);

        lblRoom.setBackground(new java.awt.Color(254, 254, 254));
        lblRoom.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lblRoom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/down.png"))); // NOI18N
        lblRoom.setText("                                      Modify Orders");
        lblRoom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblRoom.setOpaque(true);
        lblRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRoomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRoomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRoomMouseExited(evt);
            }
        });
        jPanel1.add(lblRoom);

        lblRoom3.setBackground(new java.awt.Color(254, 254, 254));
        lblRoom3.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lblRoom3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRoom3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/down.png"))); // NOI18N
        lblRoom3.setText("                              Modify Guest Details");
        lblRoom3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblRoom3.setOpaque(true);
        lblRoom3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRoom3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRoom3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRoom3MouseExited(evt);
            }
        });
        jPanel1.add(lblRoom3);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 232, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 377, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblRoom2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRoom2MouseClicked
        settleAutoCommit();

        lblRoom2.setForeground(Color.red);
        lblRoom.setForeground(Color.black);
        lblRoom3.setForeground(Color.black);

        try {
            modifyRoomReservePanel p = new modifyRoomReservePanel();
            mainPanel1.removeAll();
            mainPanel1.repaint();
            mainPanel1.revalidate();
            p.setSize(mainPanel1.getSize());
            mainPanel1.add(p);
        } catch (Exception ex) {
            Logger.getLogger(modReservePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblRoom2MouseClicked

    private void lblRoom2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRoom2MouseExited
        lblRoom2.setBackground(Color.white);
        lblRoom2.setOpaque(true);// TODO add your handling code here:
    }//GEN-LAST:event_lblRoom2MouseExited

    private void lblRoom2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRoom2MouseEntered
        //     lblRoom.setBackground(new Color(204,204,255));

        lblRoom2.setBackground(new Color(204, 204, 255));
        lblRoom2.setOpaque(true);    // TODO add your handling code here:
    }//GEN-LAST:event_lblRoom2MouseEntered

    private void lblRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRoomMouseClicked
        settleAutoCommit();

        try {
            lblRoom.setForeground(Color.red);
            lblRoom2.setForeground(Color.black);
            lblRoom3.setForeground(Color.black);

            modifyOrders p = new modifyOrders();

            mainPanel1.removeAll();
            mainPanel1.repaint();
            mainPanel1.revalidate();
            p.setSize(mainPanel1.getSize());
            mainPanel1.add(p);
        } catch (Exception ex) {
            Logger.getLogger(modReservePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblRoomMouseClicked

    private void lblRoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRoomMouseExited
        lblRoom.setBackground(Color.white);
        lblRoom.setOpaque(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblRoomMouseExited

    private void lblRoomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRoomMouseEntered
        lblRoom.setBackground(new Color(204, 204, 255));
        lblRoom.setOpaque(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRoomMouseEntered

    private void lblRoom3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRoom3MouseClicked
        try {
            settleAutoCommit();

            lblRoom3.setForeground(Color.red);
            lblRoom.setForeground(Color.black);
            lblRoom2.setForeground(Color.black);

            modifyGuestPanel p = new modifyGuestPanel();
            mainPanel1.removeAll();
            mainPanel1.repaint();
            mainPanel1.revalidate();
            p.setSize(mainPanel1.getSize());
            mainPanel1.add(p);
// TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(modReservePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblRoom3MouseClicked

    private void lblRoom3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRoom3MouseExited
        lblRoom3.setBackground(Color.white);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRoom3MouseExited

    private void lblRoom3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRoom3MouseEntered
        lblRoom3.setBackground(new Color(204, 204, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRoom3MouseEntered

    private void txtRoomPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomPriceActionPerformed

    private void txtDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDayActionPerformed

    private void btnEdit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEdit1MouseExited
        btnEdit1.setForeground(Color.white);     // TODO add your handling code here:
    }//GEN-LAST:event_btnEdit1MouseExited

    private void btnEdit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEdit1MouseEntered
        btnEdit1.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_btnEdit1MouseEntered

    private void btnEdit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEdit1MouseClicked
        if (txtNewPrice.getText().equals("0.0") || txtDesription.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Sorry! Incomplete...", "Modify Reservation", JOptionPane.WARNING_MESSAGE);

        } else {
            update();

        }// TODO add your handling code here:
    }//GEN-LAST:event_btnEdit1MouseClicked

    private void lblDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteMouseEntered
        lblDelete.setForeground(Color.black);            // TODO add your handling code here:
    }//GEN-LAST:event_lblDeleteMouseEntered

    private void lblDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteMouseExited
        lblDelete.setForeground(Color.white);      // TODO add your handling code here:
    }//GEN-LAST:event_lblDeleteMouseExited

    private void lblDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteMouseClicked
        if (txtRoom.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Sorry! Incomplete...", "Modify Reservation", JOptionPane.WARNING_MESSAGE);

        } else {
            String rid = txtRoom.getText();

            String rsid = (String) comboRsid.getSelectedItem();

            try {
                reportDeleteOrders();
                boolean r1 = resvCntrl.delete(rsid);
                if (r1) {

                    JOptionPane.showMessageDialog(null, "Deleted");

                    comboRsid.removeAllItems();
                    rsidLoard();
                    comboRsidItemStateChanged();

                } else {
                    JOptionPane.showMessageDialog(null, "Delete Failed");
                }

                // TODO add your handling code here:
            } catch (Exception ex) {
                Logger.getLogger(modReservePanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblDeleteMouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setForeground(Color.white);           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        reservation();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        String rid = (String) table.getValueAt(table.getSelectedRow(), 0);
        double price = (double) table.getValueAt(table.getSelectedRow(), 3);
        String des = (String) table.getValueAt(table.getSelectedRow(), 2);
        txtRoom.setText(rid);
        txtDesription.setText(des);
        dateCountReserve();
        searchPrice1();
        icon();
        double tot = (x + 1) * price;
        txtNewPrice.setText(tot + "");
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void datePickerIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datePickerIn1ActionPerformed
        Date d = datePickerIn1.getDate();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String formatDate = df.format(d);
        txtOUT.setText(formatDate);
    }//GEN-LAST:event_datePickerIn1ActionPerformed

    private void txtOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOUTActionPerformed
        String txt = txtOUT.getText();
        boolean isTel = false;

        if (txt.matches("\\d{4}-\\d{2}-\\d{2}")) {
            isTel = true;
        }

        if (isTel) {
            reservation();
        } else {

            JOptionPane.showMessageDialog(null, "invalid Date");
            txtOUT.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOUTActionPerformed

    private void comboRsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRsidActionPerformed
        comboGuest.requestFocus();//        txtGid.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_comboRsidActionPerformed

    private void comboRsidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboRsidMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0);
        //comboGuest.requestFocus();
    }//GEN-LAST:event_comboRsidMouseClicked

    private void comboRsidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboRsidItemStateChanged
        comboRsidItemStateChanged();

        //searchPrice();// TODO add your handling code here:
    }//GEN-LAST:event_comboRsidItemStateChanged

    private void comboGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGuestActionPerformed
        comboPerson.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_comboGuestActionPerformed

    private void comboGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboGuestMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0);
    }//GEN-LAST:event_comboGuestMouseClicked

    private void datePickerInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datePickerInActionPerformed
        Date d = datePickerIn.getDate();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String formatDate = df.format(d);
        txtIN.setText(formatDate);
        // TODO add your handling code here:
    }//GEN-LAST:event_datePickerInActionPerformed

    private void txtINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtINActionPerformed
        String txt = txtIN.getText();
        boolean isTel = false;

        if (txt.matches("\\d{4}-\\d{2}-\\d{2}")) {
            isTel = true;
        }

        if (isTel) {
            txtOUT.requestFocus();
        } else {

            JOptionPane.showMessageDialog(null, "invalid Date");
            txtIN.requestFocus();
        }

        //txtOUT.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtINActionPerformed

    private void comboGuestItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboGuestItemStateChanged
        try {
            String id = (String) comboGuest.getSelectedItem();
            GuestDTO list = guestCntrl.search(id);
            lblGuestName.setText(list.getName());
        } catch (Exception ex) {
            Logger.getLogger(modifyRoomReservePanel.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_comboGuestItemStateChanged

    private void lblDelete1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelete1MouseClicked
        try {
            DefaultTableModel dtm = (DefaultTableModel) table.getModel();
            dtm.setRowCount(0);
            txtNewPrice.setText(txtOldPrice.getText());
            rsidLoard();
            comboRsidItemStateChanged();
        } catch (Exception ex) {
            Logger.getLogger(modReservePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblDelete1MouseClicked

    private void lblDelete1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelete1MouseExited
        lblDelete1.setForeground(Color.white);  // TODO add your handling code here:
    }//GEN-LAST:event_lblDelete1MouseExited

    private void lblDelete1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelete1MouseEntered
        lblDelete1.setForeground(Color.black);     // TODO add your handling code here:
    }//GEN-LAST:event_lblDelete1MouseEntered

    private void comboPersonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboPersonMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0);        // TODO add your handling code here:
    }//GEN-LAST:event_comboPersonMouseClicked

    private void txtINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtINMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0);        // TODO add your handling code here:
    }//GEN-LAST:event_txtINMouseClicked

    private void txtOUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOUTMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0);        // TODO add your handling code here:
    }//GEN-LAST:event_txtOUTMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEdit1;
    private javax.swing.JComboBox comboGuest;
    private javax.swing.JComboBox comboPerson;
    private javax.swing.JComboBox<String> comboRsid;
    private org.jdesktop.swingx.JXDatePicker datePickerIn;
    private org.jdesktop.swingx.JXDatePicker datePickerIn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblDelete;
    private javax.swing.JLabel lblDelete1;
    private javax.swing.JLabel lblGuestName;
    private javax.swing.JLabel lblRoom;
    private javax.swing.JLabel lblRoom2;
    private javax.swing.JLabel lblRoom3;
    private javax.swing.JLabel lblRoomIcon;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainPanel1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtDay;
    private javax.swing.JLabel txtDesription;
    private javax.swing.JTextField txtIN;
    private javax.swing.JTextField txtNewPrice;
    private javax.swing.JTextField txtOUT;
    private javax.swing.JTextField txtOldPrice;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JTextField txtRoom;
    private javax.swing.JTextField txtRoomPrice;
    // End of variables declaration//GEN-END:variables
    public void rsidLoard() throws Exception {
        try {
            ArrayList<ReservationDTO> reserveList = resvCntrl.getAllID();
            for (int i = 0; i < reserveList.size(); i++) {
                ReservationDTO reserve = (ReservationDTO) reserveList.get(i);
                comboRsid.addItem(reserve.getRsID());
            }
        } catch (SQLException e) {
            System.out.println(e);
        } catch (ClassNotFoundException e) {
            System.out.println(e);
        }
    }

    public void clear() throws Exception {
        txtIN.setText("");
        txtOUT.setText("");
        //txtGid.setText("");
        txtRoom.setText("");
        // txtPersons.setText("");
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0);
        table.removeAll();

    }

    private void view() throws Exception {
        try {
            ArrayList<RoomDTO> roomList = roomCntrl.getAllName();
            DefaultTableModel dtm = (DefaultTableModel) table.getModel();
            dtm.setRowCount(0);
            for (RoomDTO c1 : roomList) {
                Object[] rowData = {c1.getRID(), c1.getRoom_Name(), c1.getRoom_Description(), c1.getRoom_Price()};
                dtm.addRow(rowData);
            }
        } catch (SQLException e) {
            System.out.println(e);
        } catch (ClassNotFoundException e) {
            System.out.println(e);

        }
    }

    private void edit() {
        txtRoom.setEnabled(false);
        txtRoom.setDisabledTextColor(new Color(128, 128, 128));
        txtOldPrice.setEnabled(false);
        txtOldPrice.setDisabledTextColor(new Color(128, 128, 128));
        txtNewPrice.setEnabled(false);
        txtNewPrice.setDisabledTextColor(new Color(128, 128, 128));

    }

    private void reservation() {
        try {
            ReservationDTO reserve = new ReservationDTO(txtIN.getText(), txtOUT.getText());
            ArrayList<ReservationDTO> roomList = queryCntrl.getRserveRoom(txtIN.getText(), txtOUT.getText());

            DefaultTableModel dtm = (DefaultTableModel) table.getModel();
            dtm.setRowCount(0);
            for (ReservationDTO c1 : roomList) {

               // System.out.println("***" + c1.getrID());

                //Object[] rowData = {c1.getrID()};
                RoomDTO r1 = roomCntrl.search(c1.getrID());

                Object[] row = {r1.getRID(), r1.getRoom_Name(), r1.getRoom_Description(), r1.getRoom_Price()};
                dtm.addRow(row);

            }
            int x = dtm.getRowCount();
            if (x == 0) {
                JOptionPane.showMessageDialog(null, "All Rooms are Reserve");
            }

        } catch (Exception ex) {
            Logger.getLogger(modReservePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void update() {
        try {
            String rid = txtRoom.getText();
            String rsid = (String) comboRsid.getSelectedItem();
            String gid = (String) comboGuest.getSelectedItem();
            String persons = (String) comboPerson.getSelectedItem();
            String in = txtIN.getText();
            String out = txtOUT.getText();
            double price = Double.parseDouble(txtNewPrice.getText());

            int person = Integer.parseInt(persons);
            ReservationDTO reserve = new ReservationDTO(rsid, gid, rid, person, in, out, price);
            boolean update = resvCntrl.update(reserve);
            if (update) {
                JOptionPane.showMessageDialog(null, "Update Success");
                payment();
                clear();

            } else {
                JOptionPane.showMessageDialog(null, "Update Failed");
            }
        } catch (Exception ex) {
            Logger.getLogger(modReservePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void payment() {
        String id = (String) comboRsid.getSelectedItem();
        // String in = txtIN.getText();
        // String out = txtOUT.getText();
        double old = Double.parseDouble(txtOldPrice.getText());
        double price = Double.parseDouble(txtNewPrice.getText());
        String rid = txtRoom.getText();
        String name = lblGuestName.getText();
        String in = txtIN.getText();
        String out = txtOUT.getText();
        String gid = (String) comboGuest.getSelectedItem();

        mainPanel1.removeAll();
        mainPanel1.repaint();
        mainPanel1.revalidate();
        ModifyPayment r1 = new ModifyPayment(id, old, price, rid, oldRid, in, out, name, gid);
        r1.setSize(mainPanel1.getSize());

        mainPanel1.add(r1);
    }

    private void dateCountReserve() {

        try {
            SimpleDateFormat s1 = new SimpleDateFormat("yyyy-MM-dd");
            String in1 = txtIN.getText();
            String in2 = txtOUT.getText();

            Date d1 = s1.parse(in1);
            Date d2 = s1.parse(in2);

            long diff = d2.getTime() - d1.getTime();
            x = TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);
            //System.out.println("Day : " + x);

            int y = (int) x;
            txtDay.setText(y + 1 + "");

        } catch (ParseException ex) {
            Logger.getLogger(publicPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void searchPrice() {
        try {
            String rsid=(String)comboRsid.getSelectedItem();
            String rid=txtRoom.getText();
            PaymentDTO se=payCntrl.searchId(rsid,rid);
            txtOldPrice.setText(se.getAdvance()+"");
            RoomDTO c1 = roomCntrl.search(txtRoom.getText());
            txtRoomPrice.setText(c1.getRoom_Price() + "");
        } catch (Exception ex) {
            Logger.getLogger(modReservePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void icon() {
        if (txtRoom.getText().equals("R01")) {
            txtDesription.setText("****");
            lblRoomIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/family suite a.png")));

        } else {
            if (txtRoom.getText().equals("R02")) {
                txtDesription.setText("****");
                lblRoomIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/family suite a.png")));

            } else {
                if (txtRoom.getText().equals("R03")) {
                    lblRoomIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/delux villa b.png")));

                } else {
                    if (txtRoom.getText().equals("R04")) {
                        lblRoomIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/delux double room c.png")));
                    } else {
                        if (txtRoom.getText().equals("R05")) {
                            lblRoomIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Help_48px.png")));
                        } else {
                            if (txtRoom.getText().equals("R06")) {
                                lblRoomIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Help_48px.png")));
                            }

                        }
                    }

                }
            }

        }
    }

    private void gidLoard() {
        try {
            ArrayList<GuestDTO> list = guestCntrl.getAllID();
            for (int i = 0; i < list.size(); i++) {
                GuestDTO combo = list.get(i);
                comboGuest.addItem(combo.getGID());

            }
        } catch (Exception ex) {
            Logger.getLogger(modReservePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void settleAutoCommit() {
        try {
            conn.setAutoCommit(false);
            conn.rollback();
            conn.setAutoCommit(true);
        } catch (SQLException ex) {
            Logger.getLogger(modReservePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void comboRsidItemStateChanged() {

        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0);

        String id = (String) comboRsid.getSelectedItem();
        icon();
        try {
            ReservationDTO res = resvCntrl.search(id);
            if (res != null) {
                //searchPrice();
                comboGuest.setSelectedItem(res.getgID());
                txtRoom.setText(res.getrID());
                oldRid = res.getrID();
                txtIN.setText(res.getCheck_In());
                txtOUT.setText(res.getCheck_Out());
                comboPerson.setSelectedItem(res.getPersons());
                //txtPersons.setText(res.getPersons() + "");
                txtOldPrice.setText(res.getPrice() + "");
                txtNewPrice.setText(res.getPrice() + "");
                txtDesription.setText("****");
                txtPrice.setText("****");
                dateCountReserve();
                icon();
                saveData();
            } else {

            }
        } catch (Exception ex) {
            Logger.getLogger(modReservePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        dateCountReserve();
        searchPrice();

    }

    private void reportDeleteOrders() {

        try {
            JasperReport main = (JasperReport) JRLoader.loadObject(backup.class.getResourceAsStream("/com/mangroven/hotel/jasper/reports/DeleteReserveBill.jasper"));
            Connection conn;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/MangrovenNew", "root", "4241");

            HashMap<String, Object> parameters = new HashMap<>();

            parameters.put("rsid", comboRsid.getSelectedItem() + "");
            parameters.put("pre", txtOldPrice.getText());
            parameters.put("return", txtOldPrice.getText());
            parameters.put("pay", payid);

            JasperPrint fill = JasperFillManager.fillReport(main, parameters, conn);
            //JasperPrint filledReport = JasperFillManager.fillReport(mainReport, parameters, new JREmptyDataSource());
            JasperReportView view = new JasperReportView(fill);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(backup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(backup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(backup.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void saveData() {

        String rsid = (String) comboRsid.getSelectedItem();
        PaymentDTO payList = payCntrl.searchId(rsid, oldRid);
        System.out.println(rsid + " " + oldRid);
        System.out.println(payList);
        payid = payList.getPyid();

    }

    private void searchPrice1() {
         try {
            
            RoomDTO c1 = roomCntrl.search(txtRoom.getText());
            txtRoomPrice.setText(c1.getRoom_Price() + "");
        } catch (Exception ex) {
            Logger.getLogger(modReservePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
