/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mangroven.hotel.view.jpanel;

import com.mangroven.hotel.jasper.main.JasperReportView;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author Athukorala
 */
public class reports extends javax.swing.JPanel {

    /**
     * Creates new form reports
     */
    public reports() {
        initComponents();
        in.setVisible(false);
        out.setVisible(false);
        report();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblRoom2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        room = new javax.swing.JLabel();
        foodPackge = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        guest = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        guest2 = new javax.swing.JLabel();
        txtIn = new com.toedter.calendar.JDateChooser();
        txtOut = new com.toedter.calendar.JDateChooser();
        in = new javax.swing.JLabel();
        out = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIn1 = new com.toedter.calendar.JDateChooser();
        txtOut1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        roomDate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIn2 = new com.toedter.calendar.JDateChooser();
        txtOut2 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        packageDate = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        lblRoom2.setBackground(new java.awt.Color(254, 254, 254));
        lblRoom2.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lblRoom2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRoom2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/down.png"))); // NOI18N
        lblRoom2.setText("                                            Search And Find The Reports");
        lblRoom2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblRoom2.setOpaque(true);
        lblRoom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRoom2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRoom2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRoom2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRoom2, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRoom2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(243, 243, 243));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(168, 1, 1));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/lock.png"))); // NOI18N
        jLabel3.setText("   Summary Of Report");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/ok.gif"))); // NOI18N
        jLabel4.setText("      Find the Best Rooms Of The All Time");

        room.setBackground(new java.awt.Color(255, 255, 255));
        room.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        room.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Accounting_30px.png"))); // NOI18N
        room.setText("     Report");
        room.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        room.setOpaque(true);
        room.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roomMouseExited(evt);
            }
        });

        foodPackge.setBackground(new java.awt.Color(255, 255, 255));
        foodPackge.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        foodPackge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Accounting_30px.png"))); // NOI18N
        foodPackge.setText("     Report");
        foodPackge.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        foodPackge.setOpaque(true);
        foodPackge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodPackgeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                foodPackgeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                foodPackgeMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/ok.gif"))); // NOI18N
        jLabel6.setText("      Find the Best Food Packages Of The All Time");

        guest.setBackground(new java.awt.Color(255, 255, 255));
        guest.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        guest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Accounting_30px.png"))); // NOI18N
        guest.setText("     Report");
        guest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        guest.setOpaque(true);
        guest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guestMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/ok.gif"))); // NOI18N
        jLabel7.setText("      Find the Best Guest and Calculate Total Finance");

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/ok.gif"))); // NOI18N
        jLabel8.setText("      Fast Moving Package Of the ");

        guest2.setBackground(new java.awt.Color(255, 255, 255));
        guest2.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        guest2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Accounting_30px.png"))); // NOI18N
        guest2.setText("     Report");
        guest2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        guest2.setOpaque(true);
        guest2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guest2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guest2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guest2MouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/IMG-20170324-WA0003.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/ok.gif"))); // NOI18N
        jLabel9.setText("      Calculate Total Income Or Cost in this Date Ranges");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("To ");

        roomDate.setBackground(new java.awt.Color(255, 255, 255));
        roomDate.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        roomDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Accounting_30px.png"))); // NOI18N
        roomDate.setText("     Report");
        roomDate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        roomDate.setOpaque(true);
        roomDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomDateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roomDateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roomDateMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/ok.gif"))); // NOI18N
        jLabel10.setText("      Fast Moving Room Of the ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("To ");

        packageDate.setBackground(new java.awt.Color(255, 255, 255));
        packageDate.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        packageDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Accounting_30px.png"))); // NOI18N
        packageDate.setText("     Report");
        packageDate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        packageDate.setOpaque(true);
        packageDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                packageDateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                packageDateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                packageDateMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(45, 164, 53));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/WhatsApp_20px.png"))); // NOI18N
        jLabel11.setText("+94778533935");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(58, 16, 141));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/Facebook_20px.png"))); // NOI18N
        jLabel12.setText(" Tharindu Dananjaya Athukorala");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIn2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtOut2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(packageDate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtOut, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(guest, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(foodPackge, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(room, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(roomDate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(16, 16, 16)
                        .addComponent(guest2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(in, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(out, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 95, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel11)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(out, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)))))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodPackge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guest2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtOut1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(roomDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(packageDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOut2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblRoom2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRoom2MouseClicked

    }//GEN-LAST:event_lblRoom2MouseClicked

    private void lblRoom2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRoom2MouseEntered
        lblRoom2.setBackground(new Color(204, 204, 255));
        lblRoom2.setOpaque(true);    // TODO add your handling code here:
    }//GEN-LAST:event_lblRoom2MouseEntered

    private void lblRoom2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRoom2MouseExited
        lblRoom2.setBackground(Color.white);
        lblRoom2.setOpaque(true);// TODO add your handling code here:
    }//GEN-LAST:event_lblRoom2MouseExited

    private void roomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomMouseClicked
        bestRooms();
    }//GEN-LAST:event_roomMouseClicked

    private void roomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomMouseEntered
        room.setForeground(Color.red);         // TODO add your handling code here:
    }//GEN-LAST:event_roomMouseEntered

    private void roomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomMouseExited
        room.setForeground(Color.black);   // TODO add your handling code here:
    }//GEN-LAST:event_roomMouseExited

    private void foodPackgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodPackgeMouseClicked
        bestPackage();   // TODO add your handling code here:
    }//GEN-LAST:event_foodPackgeMouseClicked

    private void foodPackgeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodPackgeMouseEntered
        foodPackge.setForeground(Color.red);        // TODO add your handling code here:
    }//GEN-LAST:event_foodPackgeMouseEntered

    private void foodPackgeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodPackgeMouseExited
        foodPackge.setForeground(Color.black);    // TODO add your handling code here:
    }//GEN-LAST:event_foodPackgeMouseExited

    private void guestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guestMouseClicked
        bestGuest();     // TODO add your handling code here:
    }//GEN-LAST:event_guestMouseClicked

    private void guestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guestMouseEntered
        guest.setForeground(Color.red);        // TODO add your handling code here:
    }//GEN-LAST:event_guestMouseEntered

    private void guestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guestMouseExited
        guest.setForeground(Color.black);  // TODO add your handling code here:
    }//GEN-LAST:event_guestMouseExited

    private void guest2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guest2MouseClicked

        in.setText(txtIn.getDate() + "");

        out.setText(txtOut.getDate() + "");

        if (in.getText().equals("null") || out.getText().equals("null")) {
            JOptionPane.showMessageDialog(null, " Not Complete! Please Select the Dates.. ", "Error!", JOptionPane.WARNING_MESSAGE);
        } else {
            searchIncome();
            in.setText("");
            out.setText("");
        }
    }//GEN-LAST:event_guest2MouseClicked

    private void guest2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guest2MouseEntered
        guest2.setForeground(Color.red);     // TODO add your handling code here:
    }//GEN-LAST:event_guest2MouseEntered

    private void guest2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guest2MouseExited
        guest2.setForeground(Color.black);     // TODO add your handling code here:
    }//GEN-LAST:event_guest2MouseExited

    private void roomDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomDateMouseClicked
        in.setText(txtIn1.getDate() + "");

        out.setText(txtOut1.getDate() + "");

        if (in.getText().equals("null") || out.getText().equals("null")) {
            JOptionPane.showMessageDialog(null, " Not Complete! Please Select the Dates.. ", "Error!", JOptionPane.WARNING_MESSAGE);
        } else {
            bestRoomsDate();
            in.setText("");
            out.setText("");
        }
    }//GEN-LAST:event_roomDateMouseClicked

    private void roomDateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomDateMouseEntered
        roomDate.setForeground(Color.red);
    }//GEN-LAST:event_roomDateMouseEntered

    private void roomDateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomDateMouseExited
        roomDate.setForeground(Color.black);
    }//GEN-LAST:event_roomDateMouseExited

    private void packageDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_packageDateMouseClicked
        in.setText(txtIn2.getDate() + "");

        out.setText(txtOut2.getDate() + "");

        if (in.getText().equals("null") || out.getText().equals("null")) {
            JOptionPane.showMessageDialog(null, " Not Complete! Please Select the Dates.. ", "Error!", JOptionPane.WARNING_MESSAGE);
        } else {
            bestPackageDate();
            in.setText("");
            out.setText("");
        }
    }//GEN-LAST:event_packageDateMouseClicked

    private void packageDateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_packageDateMouseEntered
        packageDate.setForeground(Color.red);
    }//GEN-LAST:event_packageDateMouseEntered

    private void packageDateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_packageDateMouseExited
        packageDate.setForeground(Color.black);
    }//GEN-LAST:event_packageDateMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel foodPackge;
    private javax.swing.JLabel guest;
    private javax.swing.JLabel guest2;
    private javax.swing.JLabel in;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblRoom2;
    private javax.swing.JLabel out;
    private javax.swing.JLabel packageDate;
    private javax.swing.JLabel room;
    private javax.swing.JLabel roomDate;
    private com.toedter.calendar.JDateChooser txtIn;
    private com.toedter.calendar.JDateChooser txtIn1;
    private com.toedter.calendar.JDateChooser txtIn2;
    private com.toedter.calendar.JDateChooser txtOut;
    private com.toedter.calendar.JDateChooser txtOut1;
    private com.toedter.calendar.JDateChooser txtOut2;
    // End of variables declaration//GEN-END:variables

    private void bestRooms() {
        try {
            JasperReport main = (JasperReport) JRLoader.loadObject(reports.class.getResourceAsStream("/com/mangroven/hotel/jasper/reports/bestRooms.jasper"));
            Connection conn;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/MangrovenNew", "root", "4241");
            JasperPrint fill = JasperFillManager.fillReport(main, null, conn);
            //JasperPrint filledReport = JasperFillManager.fillReport(mainReport, parameters, new JREmptyDataSource());
            JasperReportView view = new JasperReportView(fill);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void bestPackage() {
        try {
            JasperReport main = (JasperReport) JRLoader.loadObject(reports.class.getResourceAsStream("/com/mangroven/hotel/jasper/reports/bestFoodPackages.jasper"));
            Connection conn;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/MangrovenNew", "root", "4241");
            JasperPrint fill = JasperFillManager.fillReport(main, null, conn);
            //JasperPrint filledReport = JasperFillManager.fillReport(mainReport, parameters, new JREmptyDataSource());
            JasperReportView view = new JasperReportView(fill);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void bestGuest() {
        try {
            JasperReport main = (JasperReport) JRLoader.loadObject(reports.class.getResourceAsStream("/com/mangroven/hotel/jasper/reports/bestGuest.jasper"));
            Connection conn;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/MangrovenNew", "root", "4241");
            JasperPrint fill = JasperFillManager.fillReport(main, null, conn);
            //JasperPrint filledReport = JasperFillManager.fillReport(mainReport, parameters, new JREmptyDataSource());
            JasperReportView view = new JasperReportView(fill);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchIncome() {
        Date d = txtIn.getDate();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String formatDate = df.format(d);
        String date1 = formatDate;

        Date d2 = txtOut.getDate();
        String formatDate2 = df.format(d2);
        String date2 = formatDate2;

        try {
            JasperReport main = (JasperReport) JRLoader.loadObject(reports.class.getResourceAsStream("/com/mangroven/hotel/jasper/reports/searchIncomeOrCost.jasper"));
            Connection conn;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/MangrovenNew", "root", "4241");

            HashMap<String, Object> parameters = new HashMap<>();
            parameters.put("in", date1);
            parameters.put("out", date2);

            JasperPrint fill = JasperFillManager.fillReport(main, parameters, conn);
            //JasperPrint filledReport = JasperFillManager.fillReport(mainReport, parameters, new JREmptyDataSource());
            JasperReportView view = new JasperReportView(fill);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void bestRoomsDate() {
        Date d = txtIn1.getDate();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String formatDate = df.format(d);
        String date1 = formatDate;

        Date d2 = txtOut1.getDate();
        String formatDate2 = df.format(d2);
        String date2 = formatDate2;

        try {
            JasperReport main = (JasperReport) JRLoader.loadObject(reports.class.getResourceAsStream("/com/mangroven/hotel/jasper/reports/bestRoomsOnDate.jasper"));
            Connection conn;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/MangrovenNew", "root", "4241");

            HashMap<String, Object> parameters = new HashMap<>();
            parameters.put("in", date1);
            parameters.put("out", date2);

            JasperPrint fill = JasperFillManager.fillReport(main, parameters, conn);
            //JasperPrint filledReport = JasperFillManager.fillReport(mainReport, parameters, new JREmptyDataSource());
            JasperReportView view = new JasperReportView(fill);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void bestPackageDate() {
        Date d = txtIn2.getDate();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String formatDate = df.format(d);
        String date1 = formatDate;

        Date d2 = txtOut2.getDate();
        String formatDate2 = df.format(d2);
        String date2 = formatDate2;

        try {
            JasperReport main = (JasperReport) JRLoader.loadObject(reports.class.getResourceAsStream("/com/mangroven/hotel/jasper/reports/bestFoodPackagesOnDate.jasper"));
            Connection conn;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/MangrovenNew", "root", "4241");

            HashMap<String, Object> parameters = new HashMap<>();
            parameters.put("in", date1);
            parameters.put("out", date2);

            JasperPrint fill = JasperFillManager.fillReport(main, parameters, conn);
            //JasperPrint filledReport = JasperFillManager.fillReport(mainReport, parameters, new JREmptyDataSource());
            JasperReportView view = new JasperReportView(fill);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void report() {

        Timer tmrAnimation = new Timer(500, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                jLabel1.setLocation(jLabel1.getLocation().y + 800, jLabel1.getLocation().y);
                if (jLabel1.getLocation().y > reports.this.getHeight()) {
                    jLabel1.setLocation(0, 0);
                }
            }

            
        });
        tmrAnimation.start();
    }

}
